name: Build and Deploy Nuxt ğŸ¤©

on:
  push:
    branches:
      - 'master'
    paths:
      - 'nuxt/**'
      - '!nuxt/version.txt'
  workflow_dispatch: { }

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build & Deploy Nuxt ğŸ¤©
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU ğŸŒ±
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx ğŸŒ±
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry ğŸ’»ğŸ–±
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker â›
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/nuxt
      - name: Build and push Docker image âš’
        id: build-push-image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./nuxt
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: lowercase-repo
        name: Read Docker Image Identifiers ğŸ“š
        run: echo ::set-output name=repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Setup Kustomize ğŸ—
        uses: imranismail/setup-kustomize@v1
      - name: Kustomize Nuxt Image ğŸ–ŒğŸ¨
        run: |
          cd ./gitops
          kustomize edit set image ${{ env.REGISTRY }}/${{ steps.lowercase-repo.outputs.repo }}/nuxt@${{steps.build-push-image.outputs.digest}}
      - name: Create Pull Request ğŸ‰ğŸ‰ğŸ‰
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Nuxt Container ğŸ‰ğŸ‰ğŸ‰
          delete-branch: true
          branch: bot/version-upgrade
          base: master
          title: Update Containers
